In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/umang/Desktop/Fast DA/data/raw_jobs.csv")

In [3]:
df.head()

,company,experiance,city,salary,job_detail,required_skill
0,Amgen Inc,0 - 3 years,Hyderabad,0_to_3L,['Role: Configuration and Deployment Managemen...,"['cyber security', 'microsoft azure', 'it oper..."
1,Raksha Technologies,0 - 3 years,Chennai( Velachery ),0_to_3L,"['Role: IT & Information Security - Other', 'I...","['Log Analysis', 'SOC', 'Qradar', 'Security Mo..."
2,Leading Client,0 - 1 years,"Pune, Bengaluru",0_to_3L,"['Role: Cyber Security', 'Industry Type: Hardw...","['Cyber Security', 'SOC', 'Penetration Testing..."
3,Amgen Inc,0 - 3 years,Hyderabad,0_to_3L,"['Role: Security Engineer / Analyst', 'Industr...","['security operations', 'soc', 'linux', 'vecto..."
4,Sharkstriker,0 - 1 years,Ahmedabad,0_to_3L,"['Role: Ex-Serviceman Unarmed Security Guard',...","['security analysis', 'cyber security', 'netwo..."

In [4]:
df.tail()

,company,experiance,city,salary,job_detail,required_skill
15804,Aftershoot,3 - 5 years,New Delhi,50L_to_75L,"['Role: Product Designer', 'Industry Type: Sof...","['User research', 'Photography', 'Product engi..."
15805,Cvent,10 - 13 years,"Gurugram, Bengaluru",50L_to_75L,"['Role: UX Design Manager', 'Industry Type: So...","['Content Designing', 'Enterprise Software', '..."
15806,Good Co India,2 - 6 years,"Singapore, Germany, United Arab Emirates","70,000-175,000 P.A.","['Role: Full Stack Developer', 'Industry Type:...","['Node.Js', 'Javascript', 'React.Js', 'Docker'..."
15807,Ninja Van,6 - 11 years,Hyderabad,50L_to_75L,['Role: Blockchain Quality Assurance Engineer'...,"['Computer science', 'Front end', 'Version con..."
15808,VHR Professional Services,7 - 12 years,"Singapore, Canada, United Kingdom (UK)",75-85 Lacs P.A.,"['Role: UI / UX Designer', 'Industry Type: IT ...","['User Experience Design', 'Product Design', '..."

In [5]:
df.describe()

,company,experiance,city,salary,job_detail,required_skill
count,15732,15809,15809,15809,15809,15809
unique,4147,167,1152,469,5419,13785
top,Accenture,5 - 10 years,Bengaluru,3L_to_6L,"['Role: Back End Developer', 'Industry Type: I...","['DynaTrace', 'Ansible', 'APM', 'Monitoring To..."
freq,2339,1496,3843,4054,521,20

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15809 entries, 0 to 15808
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   company         15732 non-null  object
 1   experiance      15809 non-null  object
 2   city            15809 non-null  object
 3   salary          15809 non-null  object
 4   job_detail      15809 non-null  object
 5   required_skill  15809 non-null  object
dtypes: object(6)
memory usage: 741.2+ KB

In [7]:
rows_without_company_name = df[df['company'].isna()]
rows_without_company_name

,company,experiance,city,salary,job_detail,required_skill
1931,NaN,5 - 10 years,Bengaluru,6L_to_10L,"['Role: Machine Learning Engineer', 'Industry ...","['machine learning', 'tableau', 'machine learn..."
2086,NaN,2 - 3 years,Hyderabad,6L_to_10L,"['Role: Business Analyst', 'Industry Type: Adv...","['Social media marketing', 'Public relations',..."
2213,NaN,5 - 10 years,Bengaluru,6L_to_10L,"['Role: Data Science & Analytics - Other', 'In...","['O2C', 'SAP', 'Order To Cash', 'Data Analytic..."
2357,NaN,3 - 6 years,Bengaluru,10L_to_15L,"['Role: Analytics Consultant', 'Industry Type:...","['data modeling', 'balance sheet', 'data analy..."
2459,NaN,7 - 10 years,Hyderabad,10L_to_15L,"['Role: Data Engineer', 'Industry Type: IT Ser...","['Data Quality', 'Data Visualization', 'Data M..."
...,...,...,...,...,...,...
14748,NaN,2 - 7 years,"Kolkata, Gurugram, Bengaluru",3-5 Lacs P.A.,"['Role: Interior Designer', 'Industry Type: Ar...","['Interior Designing', 'Sketchup', 'Furniture ..."
14773,NaN,2 - 7 years,"Hyderabad, Pune, Chennai",3-5 Lacs P.A.,"['Role: Interior Designer', 'Industry Type: Ar...","['Interior Designer', 'Sketchup', 'Furniture D..."
14798,NaN,3 - 8 years,Mumbai (All Areas),4-8 Lacs P.A.,"['Role: Interior Designer', 'Industry Type: Ar...","['Sketchup', 'Interior Designing', 'Modular Fu..."
15460,NaN,2 - 7 years,Guwahati,6L_to_10L,"['Role: Program Manager - Technology / IT', 'I...","['Product Development', 'product lifecycle man..."
15708,NaN,8 - 12 years,"Hyderabad, Pune, Delhi / NCR",30-40 Lacs P.A.,"['Role: Full Stack Developer', 'Industry Type:...","['Node.Js', 'Microservices', 'React.Js', 'LLM'..."

In [8]:
df['company'] = (df['company']
                .astype(str)
                .str.strip()
                .str.replace(r'\s+', ' ', regex = True)
                .str.lower()
                )

company_map = {
    "tata consultancy services": "tcs",
    "tata consultancy service": "tcs",
    "tcs": "tcs",
    "t.c.s.": "tcs",
    "infosys limited": "infosys",
    "google llc": "google",
    'sankhyana consultancy services':'scs'
}

df['company'] = df['company'].replace(company_map)

In [9]:
keywords = ['hiring', 'client', 'firm', 'leading', 'mnc', 'not available']
max_words = 6

def clean_company_name(name):
    if pd.isna(name) or any(word in name.lower() for word in keywords) or len(name.split()) > max_words:
        return "unknown company"
    return name

df['company'] = df['company'].apply(clean_company_name)
print(df['company'])

0                        amgen inc
1              raksha technologies
2                  unknown company
3                        amgen inc
4                     sharkstriker
                   ...
15804                   aftershoot
15805                        cvent
15806                good co india
15807                    ninja van
15808    vhr professional services
Name: company, Length: 15809, dtype: object

In [10]:
df['job_tittle'] = (
    df['job_detail']
      .str.split("Role:").str[1]
      .str.split("',").str[0]
      .str.split('-').str[0]     # removes "- other"
      .str.split('(').str[0]
      .str.split('/').str[0]
      .str.strip()
)

In [11]:
df.job_tittle.unique().tolist()

['Configuration and Deployment Management',
 'IT & Information Security',
 'Cyber Security',
 'Security Engineer',
 'Ex',
 'System Security Engineer',
 'IT Security',
 'System Analyst',
 'Security Officer',
 'Network',
 'Business Development Manager',
 'Technical Architect',
 'IT Support',
 'System Administrator',
 'Accountant',
 'Network Manager',
 'Application Security Engineer',
 'Embedded Systems Engineer',
 'Design Engineer',
 'IT Infrastructure Services',
 'Security Architect',
 'Security Testing Engineer',
 'Manual Test Engineer',
 'Full Stack Developer',
 'Key Account Manager',
 'Insurance Sales',
 'Sales Support & Operations',
 'Technical Support',
 'Content Creation',
 'Pre Sales Consultant',
 'Customer Onboarding',
 'Business Development Executive',
 'Security Auditor',
 'Software Development',
 'Hardware Installation & Maintenance',
 'Back Office Executive',
 'Desktop Engineer',
 'Data Platform Engineer',
 'Chat Support',
 'Digital Marketing',
 'DevOps Engineer',
 'Strategic & Top Management',
 'Back End Developer',
 'IT Security Consultant',
 'Infrastructure Architect',
 'Quality Assurance and Testing',
 'Customer Success Associate',
 'Email Support',
 'Teaching & Training',
 'Post Silicon Test Engineer',
 'Blockchain Quality Assurance Engineer',
 'Release Engineer',
 'Technical Lead',
 'Mobile',
 'Assistant Professor',
 'Technical Consultant',
 'Technical Operations',
 'Technical Trainer',
 'Manager Information Security',
 'Network Security Engineer',
 'DevSec Engineer',
 'Security Administrator',
 'IT Consulting',
 'Research & Development',
 'Cloud System Administration',
 'Risk Management & Compliance',
 'DevOps Consultant',
 'Security Supervisor',
 'Database Administrator',
 'Application Engineer',
 'Financial Analyst',
 'Data Engineer',
 'Data warehouse Developer',
 'Operational Risk',
 'Taxation Executive',
 'Other',
 'IT Operations Management',
 'Branch Sales Manager',
 'Non Tech Support',
 'Lead Generation',
 'Full Stack Data Scientist',
 'Enterprise & B2B Sales',
 'Branch Sales Executive',
 'Front End Developer',
 'Risk Consultant',
 'Hardware and Networks',
 'HR Generalist',
 'Business Analyst',
 'Account',
 'Academic Coordinator',
 'Data Analyst',
 'IT Network',
 'Pre Sales Engineer',
 'Data Centre Ops and Server Management',
 'Software Developer in Test',
 'Operations',
 'Team Lead',
 'Head',
 'Diagnostic Molecular Scientist',
 'Service Delivery',
 'Treasury Executive',
 'Product Manager',
 'Direct Sales Executive',
 'BI Developer',
 'Quality Assurance',
 'Security Consultant',
 'Risk Analyst',
 'Chief Information Security Officer',
 'Subject',
 'Business Intelligence & Analytics',
 'Manufacturing Engineering Manager',
 'Practice Manager',
 'Associate',
 'Incident Management',
 'Site Reliability Engineer',
 'PMO Executive',
 'Enterprise Sales Manager',
 'Customer Success, Service & Operations',
 'Aviation & Aerospace',
 'Field Service Engineer',
 'Managing Editor',
 'BD',
 'Sr. Consultant',
 'Insurance Agent',
 'Unarmed Security Guard',
 'Principal Program Manager',
 'Search Engineer',
 'Project Coordinator',
 'DevOps',
 'IT Project Lead',
 'Internal Auditor',
 'IT Audit',
 'Investment Banking Associate',
 'Customer Success Manager',
 'QA Team Manager',
 'ERP Architect',
 'Customer Engagement',
 'CRM Architect',
 'Technology',
 'Data Science & Analytics',
 'Solution Architect',
 'Test Architect',
 'Other Consulting',
 'Advertising Management',
 'Regional Sales Manager',
 'Design Team Lead',
 'CTO',
 'Professor',
 'Hardware Platform Engineer',
 'Engineering Manager',
 'Relationship Manager',
 'NLP',
 'Test Analyst',
 'Other Program',
 'Customer Success',
 'DBA',
 'Strategy Manager',
 'Strategic Management',
 'Sales Head',
 'Program Manager',
 'Operations Consultant',
 'Audit Manager',
 'Procurement',
 'Assistant Manager',
 'Chief Compliance Officer',
 'Hardware Architect',
 'Vice',
 'Software Compliance',
 'Automation Test Engineer',
 'BFSI, Investments & Trading',
 'Machine Learning Engineer',
 'IT Project Manager',
 'Technology Product Management',
 'Data warehouse Architect',
 'Chartered Accountant',
 'Data Science & Machine Learning',
 'Analytics Consultant',
 'Data Scientist',
 'Statistician',
 'BI Architect',
 'BI Administration',
 'Analytics',
 'Computer Vision',
 'Manager',
 'Human Resources',
 'Database Developer',
 'IT Recruiter',
 'Recruitment & Talent Acquisition',
 'ERP Developer',
 'Network Service Technician',
 'Database Analyst',
 'Database Architect',
 'Corporate Training',
 'Leadership Recruiter',
 'Automation Developer',
 'Telecom',
 'Non IT Recruiter',
 'Associate Partner',
 'Performance Testing Engineer',
 'Machine Operator',
 'Project Planner',
 'Finance',
 'DevOps Manager',
 'HR Analyst',
 'Release Manager',
 'Project Manager',
 'Sales Operations',
 'Subject Matter Expert',
 'Finance & Accounting',
 'Product Operations Associate',
 'Data',
 'Treasury Operations Manager',
 'Quality Engineer',
 'Operations Support',
 'Automation Architect',
 'Finance Manager',
 'C & B Management',
 'Footwear Designer',
 'Service Head',
 'Cloud Consultant',
 'Mobile Apps Testing Engineer',
 'Staffing Management',
 'Principal Consultant',
 'Technical Product Manager',
 'Functional Consultant',
 'Automation Engineer',
 'Quality Manager',
 'Big Data Engineer',
 'Director',
 'Service Delivery Manager',
 'Database Manager',
 'Partner',
 'Service Delivery Leader',
 'Back Office',
 'Problem Management',
 'Engineering',
 'Production & Manufacturing',
 'Office Admin',
 'Front Office',
 'Administration',
 'Customer Retention',
 'IT Asset Management',
 'Purchase Executive',
 'Voice',
 'Private Equity Associate',
 'Retail & B2C Sales',
 'Customer Service',
 'Accounts Receivable Executive',
 'Service Engineer',
 'Operations, Maintenance & Support',
 'Audit & Control',
 'Shared Services',
 'Facility Manager',
 'Operations Manager',
 'Maintenance Engineer',
 'Production Engineer',
 'Treasury Analyst',
 'Product Engineer',
 'Assessment',
 'MIS Manager',
 'Procurement & Purchase',
 'Tool Room Engineer',
 'Image Consultant',
 'Change Manager',
 'Electrical Engineer',
 'Asset Operations',
 'Financial Consultant',
 'Team Leader',
 'Advisor',
 'Management Consulting',
 'Facility Management',
 'Service Manager',
 'ETL Developer',
 'Formulation Scientist',
 'Operations Engineer',
 'Tax Analyst',
 'Performance Management',
 'Front Office Executive',
 'Engagement Manager',
 'Area Sales Manager',
 'Transition Manager',
 'Strategic Sourcing Manager',
 'Production Manager',
 'QA',
 'AR VR QA Tester',
 'White Box Testing Engineer',
 'Game Tester',
 'UX Writer',
 'Quality Analyst',
 'Creative Marketing',
 'Product Analyst',
 'UI',
 'Chief Accountant',
 'Foreman',
 'Civil Engineer',
 'Growth Marketing',
 'Channel Partner',
 'Graphic Designer',
 'Administration & Staff',
 'Chemist',
 'Technical Content Developer',
 'Marketing',
 'Transportation Engineer',
 'Quality Consultant',
 'Actuarial Analyst',
 'Webmaster',
 'Implementation Manager',
 'Research Associate',
 'Industrial Engineer',
 'Mathematics Teacher',
 'Game Developer',
 'Healthcare & Life Sciences',
 'Product Design Engineer',
 'Design Verification Engineer',
 'Engineering & Manufacturing',
 'Executive Assistant',
 'Private Attorney',
 'Interior Designer',
 'Web Designer',
 'Chief Creative Officer',
 'Communication Designer',
 'Architecture & Interior Design',
 'UX, Design & Architecture',
 'Fashion Designer',
 'Illustrator',
 'Architect',
 'UX Head',
 'Game Designer',
 'Design Manager',
 'Product Designer',
 'Industrial Designer',
 'Content Designer',
 'Visual Designer',
 'Video Editor',
 'Textile Designer',
 'Draughtsman',
 '3D Visualizer',
 'Motion Graphics Designer',
 'Jewellery Designer',
 'Fashion & Accessories',
 '3D Modeller',
 'Image Editor',
 'Landscape Architect',
 'Project Architect',
 'Visualiser',
 'Supply Chain Manager',
 'Interaction Designer',
 'User Research Manager',
 'Merchandising, Retail & eCommerce',
 'Advertising & Creative',
 'Creative',
 'Social Media Marketing',
 'Animator',
 'Audit Executive',
 'Storyboard Artist',
 'Construction Engineering',
 'Process Trainer',
 'Pattern Master',
 'UX Design Manager',
 'Editing',
 'eCommerce Manager',
 'Product Head',
 'Town',
 'Art Direction',
 'User Researcher',
 'Content Management',
 'Marketing Manager',
 'Marketing Automation Specialist']

In [12]:
role_mapping = {
    "junior data analyst": "data analyst",
    "senior data analyst": "data analyst",
    "network security engineer": "network engineer",
    "business development executive": "business development",
    "junior system analyst": "systems analyst",
    "senior system analyst": "systems analyst",
    "technical support": "it support",
    "treasury analyst": "financial analyst",
    "operations manager": "operations",
    "assistant manager": "manager",
    "chief accountant": "accountant",
    "automation test engineer": "automation engineer",
    "it project lead": "it project manager",
    "private attorney": "attorney",
    "customer success manager": "customer success",
    "audit executive": "audit manager",
    "quality assurance and testing": "quality assurance"
}

In [15]:
df['job_tittle'] = df['job_tittle'].str.lower()
df['job_tittle'] = df['job_tittle'].replace(role_mapping)

# This Made a problem the very below line so taking company_clean csv in other notebook

In [17]:
df = df.rename(columns = {'city':'location'}, inplace = True)

In [ ]:
#df.to_csv('company_clean.csv', index = False)